export const GET_POSTS = "GET_POSTS";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_ERROR = "GET_POSTS_ERROR";

export const GET_COMMENTS = "GET_COMMENTS";
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const GET_COMMENTS_ERROR = "GET_COMMENTS_ERROR";

export const GET_USER = "GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCES";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const GET_USER_COMMENTS = "GET_USER_COMMENTS";
export const GET_USER_COMMENTS_SUCCESS = "GET_USER_COMMENTS_SUCCES";
export const GET_USER_COMMENTS_ERROR = "GET_USER_COMMENTS_ERROR";

export const SORT_POSTS_ASC = "SORT_POSTS_ASC";
export const SORT_POSTS_DESC = "SORT_POSTS_DESC";

export const FILTER_BY_VALUE = "FILTER_BY_VALUE";
